### ISSUE TITLE
Ошибка настройки интеграции

### ISSUE THREAD

**Issue by Karnatskiy** [MihVS/zont_ha#11]
Добрый день. После установки и ввода данных авторизации в интеграции отображается надпись "Не удалось настроить". Учетная запись Zont активна, токен работоспособный (принимается при подаче запроса через Rest Client). Лог прилагаю.

Регистратор: homeassistant.config_entries
Источник: config_entries.py:504
Первое сообщение: 08:04:42 (4 сообщений)
Последнее сообщение: 09:20:14

Error setting up entry Боровск for zont_ha
Error setting up entry 13226 for zont_ha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zont_ha/__init__.py", line 27, in async_setup_entry
    await zont.get_update(old_api=True)
  File "/config/custom_components/zont_ha/core/zont.py", line 85, in get_update
    self.data_old = account.parse_raw(text)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 549, in parse_raw
    return cls.parse_obj(obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for AccountZontOld
devices -> 2 -> widget_type
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by MihVS** [comment]
Валидация ответа не проходит. Поправлю.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/tree/v0.4.6

**Comment by Karnatskiy** [comment]
Устройства появились, спасибо!
