### ISSUE TITLE
Не удаётся добавить интеграцию в HA

### ISSUE THREAD

**Issue by asapronov** [MihVS/zont_ha#33]
Добрый день.

При попытке добавления интеграции в HA получаю такю ошибку:

> Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}

В логах сервера при этом имеем сообщения:

> 2024-11-29 13:20:54.484 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.zont_ha.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 179: return await super()._post_impl(request, data) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22
> For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
> Traceback (most recent call last):
> File "<frozen runpy>", line 198, in _run_module_as_main
> File "<frozen runpy>", line 88, in _run_code
> File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
> sys.exit(main())
> File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
> exit_code = runner.run(runtime_conf)
> File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
> return loop.run_until_complete(setup_and_run_hass(runtime_config))
> File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
> self.run_forever()
> File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
> self._run_once()
> File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
> handle._run()
> File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
> self._context.run(self._callback, *self._args)
> File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
> resp = await request_handler(request)
> File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
> return await handler(request)
> File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
> response = await handler(request)
> File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
> result = await handler(request, **request.match_info)
> File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
> return await func(self, request, *args, **kwargs)
> File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
> return await method(view, request, data, *args, **kwargs)
> File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
> return await self._post_impl(request, data)
> File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
> return await super()._post_impl(request, data)
> 2024-11-29 13:20:54.485 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration zont_ha: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)
> 2024-11-29 13:21:30.879 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration zont_ha: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)
> 2024-11-29 13:22:42.353 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration zont_ha: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)

Версия HA:
```
Core 2024.10.4
Supervisor  2024.11.4
Пользовательский интерфейс 20241002.4
```

**Comment by asapronov** [comment]
Обновление HA до версии 2024.11.3 решило проблему
