### ISSUE TITLE
Не подключается учетная запись

### ISSUE THREAD

**Issue by ibrmn** [MihVS/zont_ha#7]
Добрый день!

Спасибо за ресёрч и написание компонента! Звезду поставил)
Подскажите, пожалуйста, как решить следующую проблему...
После установки компонента и добавления учетки столкнулся с тем, что интеграция пишет "не удалось настроить", а в логах показывает следующее:

```
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 05:37:18 (2 occurrences)
Last logged: 05:38:02

Error setting up entry Home for zont_ha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zont_ha/__init__.py", line 25, in async_setup_entry
    await zont.get_update(old_api=True)
  File "/config/custom_components/zont_ha/core/zont.py", line 85, in get_update
    self.data_old = account.parse_raw(text)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 549, in parse_raw
    return cls.parse_obj(obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for AccountZontOld
devices -> 1 -> firmware_version
  none is not an allowed value (type=type_error.none.not_allowed)
devices -> 1 -> hardware_type
  none is not an allowed value (type=type_error.none.not_allowed)
```

Версия HA:
Core 2024.2.3
Supervisor 2024.02.0
Operating System 11.5
Пользовательский интерфейс 20240207.1

Upd. Пробовал переустанавливать интеграцию и заново добавлять учетку, проблему не решило.

**Comment by MihVS** [comment]
> Звезду поставил)

Благодарю.

Какое устройство используете?

**Comment by ibrmn** [comment]
ZONT H1000+ Pro

**Comment by MihVS** [comment]
Выпустил бета версию v0.4.2-beta. Попробуйте обновить и проверить.

**Comment by ibrmn** [comment]
Вот логи:

```
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 13:27:16 (1 occurrences)
Last logged: 13:27:16

Error setting up entry Home for zont_ha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zont_ha/__init__.py", line 25, in async_setup_entry
    await zont.get_update(old_api=True)
  File "/config/custom_components/zont_ha/core/zont.py", line 85, in get_update
    self.data_old = account.parse_raw(text)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 549, in parse_raw
    return cls.parse_obj(obj)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for AccountZontOld
devices -> 1 -> firmware_version
  object of type 'NoneType' has no len() (type=type_error)
```

А это ответ из апи, может поможет в чем-то:
```
{
  "devices": [
    {
      "id": 320934,
      "name": "Name",
      "model": "H1000_PRO",
      "online": true,
      "widget_type": "z3k",
      "heating_circuits": [
        {
```

**Comment by MihVS** [comment]
Попробуйте обновите бета версию до  v0.4.3-beta, должно вылечиться.

**Comment by MihVS** [comment]
Дайте знать если всё получилось.

**Comment by ibrmn** [comment]
Всё отлично! Подтянулось.
Бага закрыта :)
Скажите, а влажность с датчиков можно добавить, чтобы отображалась? А то только температуру показывает

**Comment by MihVS** [comment]
> Скажите, а влажность с датчиков можно добавить, чтобы отображалась?

Она должна прокидывать тоже. Какой датчик установлен?

**Comment by ibrmn** [comment]
Датчики ZONT МЛ-745.
Влажности в объектах нет :(

**Comment by MihVS** [comment]
Ну значит ZONT не передаёт пока в новый api эти значения. У меня проводные, от них прокидывается. Свяжусь с ними, возможно добавят.

**Comment by ibrmn** [comment]
Да, действительно посмотрел по апи, там нет влажности... обидно.
Спасибо большое за труды!
